### ISSUE TITLE
move ci.centos.org workloads from legacy cico api to new duffy api

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-infra#1769]

**Comment by evgeni** [comment]
let's try this with luna or something first.

**Comment by evgeni** [comment]
status so far:
* in https://github.com/theforeman/jenkins-jobs/pull/257 I've implemented basic "all in one pipeline" for luna
* in https://github.com/theforeman/jenkins-jobs/pull/260 I'm switching to a "real" inventory instead of a fine generated by a template

The biggest issue right now is that running `vagrant up` in parallel sometimes breaks while trying to download the same base-box multiple times in parallel:
```
[2022-09-13T09:34:33.499Z] [0;31m    /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/util/file_checksum.rb:47:in `initialize': No such file or directory @ rb_sysopen - /root/.vagrant.d/tmp/boxf4b6e814a5003f4177ccc9098d0df7e64f39b349 (Errno::ENOENT)[0m
[2022-09-13T09:34:33.499Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/util/file_checksum.rb:47:in `open'[0m
[2022-09-13T09:34:33.499Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/util/file_checksum.rb:47:in `checksum'[0m
[2022-09-13T09:34:33.499Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/box_add.rb:554:in `validate_checksum'[0m
[2022-09-13T09:34:33.499Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/box_add.rb:366:in `box_add'[0m
[2022-09-13T09:34:33.499Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/box_add.rb:292:in `add_from_metadata'[0m
[2022-09-13T09:34:33.499Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/box_add.rb:127:in `call'[0m
[2022-09-13T09:34:33.499Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'[0m
[2022-09-13T09:34:33.499Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'[0m
[2022-09-13T09:34:33.499Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'[0m
[2022-09-13T09:34:33.499Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'[0m
[2022-09-13T09:34:33.499Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'[0m
[2022-09-13T09:34:33.499Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/handle_box.rb:83:in `handle_box'[0m
[2022-09-13T09:34:33.499Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/handle_box.rb:42:in `block in call'[0m
[2022-09-13T09:34:33.499Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/handle_box.rb:36:in `synchronize'[0m
[2022-09-13T09:34:33.499Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/handle_box.rb:36:in `call'[0m
[2022-09-13T09:34:33.499Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'[0m
[2022-09-13T09:34:33.499Z] [0;31m            from /root/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.10.7/lib/vagrant-libvirt/action/handle_storage_pool.rb:63:in `call'[0m
[2022-09-13T09:34:33.499Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'[0m
[2022-09-13T09:34:33.499Z] [0;31m            from /root/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.10.7/lib/vagrant-libvirt/action/set_name_of_domain.rb:34:in `call'[0m
[2022-09-13T09:34:33.499Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'[0m
[2022-09-13T09:34:33.500Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/provision.rb:80:in `call'[0m
[2022-09-13T09:34:33.500Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'[0m
[2022-09-13T09:34:33.500Z] [0;31m            from /root/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.10.7/lib/vagrant-libvirt/action/cleanup_on_failure.rb:21:in `call'[0m
[2022-09-13T09:34:33.500Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'[0m
[2022-09-13T09:34:33.500Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:127:in `block in finalize_action'[0m
[2022-09-13T09:34:33.500Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'[0m
[2022-09-13T09:34:33.500Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'[0m
[2022-09-13T09:34:33.500Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'[0m
[2022-09-13T09:34:33.500Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'[0m
[2022-09-13T09:34:33.500Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'[0m
[2022-09-13T09:34:33.500Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/call.rb:53:in `call'[0m
[2022-09-13T09:34:33.500Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'[0m
[2022-09-13T09:34:33.500Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/box_check_outdated.rb:31:in `call'[0m
[2022-09-13T09:34:33.500Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'[0m
[2022-09-13T09:34:33.500Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/config_validate.rb:25:in `call'[0m
[2022-09-13T09:34:33.500Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'[0m
[2022-09-13T09:34:33.500Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'[0m
[2022-09-13T09:34:33.500Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'[0m
[2022-09-13T09:34:33.500Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'[0m
[2022-09-13T09:34:33.500Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'[0m
[2022-09-13T09:34:33.500Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/machine.rb:246:in `action_raw'[0m
[2022-09-13T09:34:33.500Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/machine.rb:215:in `block in action'[0m
[2022-09-13T09:34:33.500Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/environment.rb:614:in `lock'[0m
[2022-09-13T09:34:33.500Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/machine.rb:201:in `call'[0m
[2022-09-13T09:34:33.500Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/machine.rb:201:in `action'[0m
[2022-09-13T09:34:33.500Z] [0;31m            from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'[0m
```

**Comment by ekohl** [comment]
How about we create a new user for every single pipeline and use the qemu session? Then we have the inefficiency of downloading the same image multiple times, but at least we won't have concurrency issues.

**Comment by evgeni** [comment]
Yes, I'm looking into this now.

**Comment by ekohl** [comment]
We have migrated and cleaned up the old code.
